version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1.29.0

workflows:
  spritecloud-assignment: 
    jobs:
      - cypress/run:
          group: 'spriteCloud QA Assignment'
          pre-steps:
            - run:
                when: always
                name: Delete old reports
                command: rm -rf /root/project/cypress/reports/
            - run:
                when: always
                name: Make artifact directories
                command: mkdir -p /root/project/cypress/reports/
          post-steps:
            - run: 
                when: always
                name: Create mochawesome report
                command: npm run merge
            - run: 
                when: always
                name: Generate mochawesome HTML report
                command: npm run generate_mochawesome_report
            - store_artifacts:
                path: mochawesome.html
                destination: /cypress/reports
            - store_artifacts:
                path: mochawesome.json
                destination: /cypress/reports
            - run:
                when: always
                name: Upload results to Calliope Pro
                command: curl -X POST -H "x-api-key:YzI5MDY5YTU1ZTE0MDIzM2RjYWFiNmJjNzUwYTU1Y2Y1MmVmN2IxN2Y1ZmM0MWRiNmE4ZmZjMDZiMWFiZTYwOTMy" -H "multipart/form-data" -F "file[]=@mochawesome.json" "https://app.calliope.pro/api/v2/profile/3788/import?os=myos&platform=myplatform&build=mybuild"
